### ISSUE TITLE
Return 401 instead of 400 when there is an authentication error

### ISSUE THREAD

**Issue by Malizor** [Zorin95670/octo-spy#7]
The standard HTTP error code when credentials are not valid is "401 Unauthorized", not "400 Bad Request".

By default, some tools like the Ansible "uri" module actually expect an initial 401 response before retrying the query with provided credentials. This is a common behaviour to only transmit credentials when they are necessary.
So today this behaviour is broken and users have to manually force the authentication.

**Comment by Zorin95670** [comment]
I put 400 on bad header, but that seems logic after your commentary, that is 401 :)

I will fix it, and notify you on wish version is included!

**Comment by Zorin95670** [comment]
It's fix on 1.11.1 octo-spy version. I will notify you and close this issue when it's release on octo.

**Comment by Zorin95670** [comment]
Octo version 1.3.0 was release and fix this issue.
